### PR TITLE
shutdown genserver without raising exception

### LINKED ISSUE #268: Mint HTTPAdapter failure cycle spams errors
Using `k8s 2.4.0` we've been seeing a lot of errors around mint and HTTPAdapter.

To reproduce on a cluster that has things happening: 

- Start some watchs on resources.
- Then, start tailing a pod's log.
- Wait for a little bit. 
- Then, you will see some errors start to appear after a few minutes.

I've created a stand-alone repro here:
https://github.com/elliottneilclark/pod_logs

try with:

```sh
mix run -e "PodLogs.run(\"default\", \"mypodmakinglogs\")"
```

That should produce the following errors:

```
09:58:41.856 [debug] K8s.Client.Mint.HTTPAdapter Terminating HTTPAdapter GenServer #PID<0.224.0>

09:58:41.859 [warning] K8s.Client.Mint.HTTPAdapter Connection closed for reading and writing - stopping this process.

09:58:41.859 [debug] K8s.Client.Mint.HTTPAdapter Terminating HTTPAdapter GenServer #PID<0.229.0>

09:58:41.856 [error] GenServer #PID<0.219.0> terminating
** (stop) :closed
Last message: :healthcheck
State: %K8s.Client.Mint.HTTPAdapter{conn: %Mint.HTTP1{host: "127.0.0.1", port: 40451, request: nil, streaming_request: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.9>, :tls_connection, :undefined}, [#PID<0.223.0>, #PID<0.222.0>]}, transport: Mint.Core.Transport.SSL, mode: :active, scheme_as_string: "https", requests: {[], []}, state: :closed, buffer: "", proxy_headers: [], private: %{}, log: false}, requests: %{}}

09:58:41.856 [error] GenServer #PID<0.224.0> terminating
** (stop) :closed
Last message: :healthcheck
State: %K8s.Client.Mint.HTTPAdapter{conn: %Mint.HTTP1{host: "127.0.0.1", port: 40451, request: nil, streaming_request: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.10>, :tls_connection, :undefined}, [#PID<0.228.0>, #PID<0.227.0>]}, transport: Mint.Core.Transport.SSL, mode: :active, scheme_as_string: "https", requests: {[], []}, state: :closed, buffer: "", proxy_headers: [], private: %{}, log: false}, requests: %{}}

09:58:41.859 [error] GenServer #PID<0.229.0> terminating
** (stop) :closed
Last message: :healthcheck
State: %K8s.Client.Mint.HTTPAdapter{conn: %Mint.HTTP1{host: "127.0.0.1", port: 40451, request: nil, streaming_request: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.11>, :tls_connection, :undefined}, [#PID<0.233.0>, #PID<0.232.0>]}, transport: Mint.Core.Transport.SSL, mode: :active, scheme_as_string: "https", requests: {[], []}, state: :closed, buffer: "", proxy_headers: [], private: %{}, log: false}, requests: %{}}

09:58:41.862 [warning] K8s.Client.Mint.HTTPAdapter Connection closed for reading and writing - stopping this process.

09:58:41.862 [debug] K8s.Client.Mint.HTTPAdapter Terminating HTTPAdapter GenServer #PID<0.234.0>
```

### PR DESCRIPTION
**Pull request by mruoss**
When an adapter needs to be terminated, we should pass a reason that doesn't treat the termination like a crash of the process and therefore doesn't raise an exception.

refs #268 

---

#### Requirements for all pull requests

- [x] Entry in CHANGELOG.md was created

### CODE REVIEW

File: lib/k8s/client/mint/http_adapter.ex [hunk 1]
```diff
@@ -455,4 +450,23 @@ defmodule K8s.Client.Mint.HTTPAdapter do
 
     {:noreply, state}
   end
+
+  @spec shutdown_if_closed(t()) :: {:noreply, t()} | {:stop, {:shutdown, :closed}, t()}
+  defp shutdown_if_closed(state) do
+    if Mint.HTTP.open?(state.conn) or any_non_empty_buffers?(state) do
```
Comment (elliottneilclark) [inline lib/k8s/client/mint/http_adapter.ex:456]: It seems like this condition is repeated above. Would it be worth putting this into a function? Then you can also explain why the server is not shutdown even if mint has closed the connection, but there are buffers

**Review by elliottneilclark — APPROVED** [review]
Thank you, this looks good.
