### PR TITLE
make sure objects with message fields are processed

### LINKED ISSUE #231: Streams resetting resource version
We have a k8s application that streams a watch of just about every kind or resource. When there's a lot of activity we will see a lot of log spam like this:

```
15:46:24.846 mfa=K8s.Client.Runner.Stream.Watch.process_object/2 [error] K8s.Client.Runner.Stream.Watch Erronous event received from watcher: Liveness probe failed: Get "http://10.244.0.16:9090/healthz/": dial tcp 10.244.0.16:9090: connect: connection refused - resetting the resource version
15:46:24.847 mfa=K8s.Client.Runner.Stream.Watch.process_object/2 [error] K8s.Client.Runner.Stream.Watch Erronous event received from watcher: Readiness probe failed: Get "http://10.244.0.16:9090/readyz/": dial tcp 10.244.0.16:9090: connect: connection refused - resetting the resource version
15:46:24.867 mfa=K8s.Client.Runner.Stream.Watch.process_object/2 [error] K8s.Client.Runner.Stream.Watch Erronous event received from watcher: Container image "ghcr.io/aquasecurity/trivy-operator:0.11.1" already present on machine - resetting the resource version
15:46:24.879 mfa=K8s.Client.Runner.Stream.Watch.process_object/2 [error] K8s.Client.Runner.Stream.Watch Erronous event received from watcher: Created container trivy-operator - resetting the resource version
15:46:24.950 mfa=K8s.Client.Runner.Stream.Watch.process_object/2 [error] K8s.Client.Runner.Stream.Watch Erronous event received from watcher: Started container trivy-operator - resetting the resource version
```

https://github.com/coryodaniel/k8s/blob/develop/lib/k8s/client/runner/stream/watch.ex#L170 It seems like watches are resetting the version when they should just ignore that event line.

### PR DESCRIPTION
**Pull request by mruoss**
Fixes #231

### CODE REVIEW

File: lib/k8s/client/runner/stream/watch.ex [hunk 1]
```diff
@@ -192,17 +179,32 @@ defmodule K8s.Client.Runner.Stream.Watch do
...
+    # resource version already obeserved.
     {[], state}
   end
 
-  defp process_object(%{"object" => object} = new_event, state) do
+  defp process_object(%{"object" => %{"kind" => _} = object} = new_event, state) do
+    # Emit new event
     new_state = struct!(state, resource_version: object["metadata"]["resourceVersion"])
     {[new_event], new_state}
   end
```
Comment (elliottneilclark) [inline lib/k8s/client/runner/stream/watch.ex:192]: That's elegant. Nice.

**Review by elliottneilclark — APPROVED** [review]
lgtm
